### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by TimWhiting** [supabase/supabase-dart#10]
# Chore

## Describe the chore

Migrate to null safety

## Additional context

I can do the migration, just need to have the null-safe versions of postgrest-dart, realtime-dart and gotrue to be published to pub.dev.
@phamhieu

**Comment by phamhieu** [comment]
Hi @TimWhiting postgrest-dart, realtime-dart and gotrue-dart are published to latest version with null-safety support.

**Comment by oussaid1** [comment]
this is really amazing , keep up the good work ,
please Migrate to null-safety
I will make sure to spread supabase among all the devs i know ..
good luck

**Comment by TimWhiting** [comment]
It's migrated, just need to be published

**Comment by phamhieu** [comment]
deployed! I'm so sorry for dragging this version deployment.
