### ISSUE TITLE
Mock SupabaseClient.

### ISSUE THREAD

**Issue by happy-san** [supabase/supabase-dart#12]
# Feature request

## Is your feature request related to a problem? Please describe.

Working on a little side-project to make a Todo app. It would be awesome to have a mock client to unit test my [Repository](https://github.com/happy-san/todo_supabase/blob/63595c146314f932e62ce1270c23bfbf7bda71bd/lib/core/todo_repository.dart) class.

## Describe the solution you'd like

A MockSupabaseClient that'll be useful for unit testing the code (similar to the `MockClient` from `http` package).

## Describe alternatives you've considered

Tried to create a mock, but got stuck since this gives me called `select('task, status')` on null. Also since `SupabaseQueryBuilder` isn't exposed, I can't mock the response of `from('todos')`.

```dart
void main() {
  TodoRepository repo;
  final mockClient = MockSupabaseClient();

  setUp(() {
    when(mockClient.from('todos').select('task, status').execute()).thenAnswer(
      (_) => Future.value(
        PostgrestResponse(
          data: [
            {'task': 't1', 'status': true},
            {'task': 't2', 'status': false},
          ],
          status: 200,
          error: null,
          count: null,
        ),
      ),
    );

    repo = TodoRepository(mockClient);
  });

  //...
}
```
I can help with this feature but I'll need some guidance along the way. Please let me know.

**Comment by happy-san** [comment]
Hey, @phamhieu have you considered this?

**Comment by phamhieu** [comment]
Hi @happy-san, you can use `MockClient` to write your unit test.

`client.from('todos').select('task, status').execute()` will translate into `https://supabase-url/todos?select=task,status`

You can use `MockClient` to return a json response for that url.

**Comment by happy-san** [comment]
Thanks, I'll try it out.

**Comment by phamhieu** [comment]
Sorry for confusing you with the word `MockClient`. I create an example [here](https://github.com/supabase/supabase-dart/blob/main/test/mock_test.dart)

**Comment by happy-san** [comment]
Thank you for creating an example. Didn't know that a `MockServer` could be created, awesome!

**Comment by BLipscomb** [comment]
I was wondering about building something like a mock supabase client for my tests, but it was an up-hill battle for me. I moved my database calls to a layer that just talks to the database. For example, I have a dbInsert method that I pass a table name and some records. This method is very simple and just does an insert. My business logic contains a call to dbInsert, and I can easily mock this call in my test.

**Comment by fimaljo-inunity** [comment]
_instance._initialized': You must initialize the supabase instance before calling Supabase. how to solve this this error showing while unit test and we using supabase only for aythentication and access token
