### ISSUE TITLE
Getx Example

### ISSUE THREAD

**Issue by faststare08** [supabase/supabase-dart#13]
# Feature request

I want to clone a todo app with getx but I have hard time to implement Authorization Controller with supabase.

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by nomanmurtaza786** [comment]
I think we should post this in getx discord.

**Comment by phamhieu** [comment]
Hope this helps https://dev.to/adityasubrahmanyabhat/implementing-auth-in-flutter-using-supabase-and-getx-1m14

**Comment by faststare08** [comment]
> Hope this helps https://dev.to/adityasubrahmanyabhat/implementing-auth-in-flutter-using-supabase-and-getx-1m14

thank you.
