### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by carlomigueldy** [supabase/supabase-dart#16]
# Bug report

## Describe the bug

When I query from a table "servers", it returns 500. I think this is coming from the `SupabaseClient`

```
{data: null, status: 500, error: {message: Null check operator used on a null value, details: null, hint: null, code: _CastError}, count: null}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a Flutter project and a Supabase project
2. Configure the Flutter project that will interact with the Supabase project (Setup SUPBASE_URL and SUPABASE_SECRET)
3. Read records from any table of your Supabase project
4. `{data: null, status: 500, error: {message: Null check operator used on a null value, details: null, hint: null, code: _CastError}, count: null}`

## Expected behavior

It should return me an array of JSON objects. And status code of `200` and not `500`.

## Screenshots

This is my supabase client setup

![image](https://user-images.githubusercontent.com/45052332/115098234-7d6ef580-9f61-11eb-8853-8561fafed277.png)

This is my query from an abstract class, then my `ServerService` class extends from it.

![image](https://user-images.githubusercontent.com/45052332/115098229-721bca00-9f61-11eb-9801-6edbb1802951.png)

Then here is where I trigger the call to Supabase API

![image](https://user-images.githubusercontent.com/45052332/115098241-8a8be480-9f61-11eb-98d7-e41432304d96.png)

Tap and call method

![image](https://user-images.githubusercontent.com/45052332/115098246-9081c580-9f61-11eb-84b1-3ffa5c15e932.png)

## System information

- OS: Windows
- Version of supabase-dart: 0.0.1-dev.11
- Version of Node.js: [e.g. 10.10.0]

Flutter doctor

![image](https://user-images.githubusercontent.com/45052332/115098310-f79f7a00-9f61-11eb-92d5-0667997f4696.png)

## Additional context

In case you might need to see it for yourself, here is my repository link. https://github.com/carlomigueldy/flutter-web-discord-clone

I love supabase since it is a serverless and uses Postgres, I love relational databases :) So thanks for creating that decision instead of going NoSQL.

**Comment by thalkz** [comment]
I cloned your project and I'm getting the same error message. It looks like an exception is thrown in the `postgrest` package on [this line](https://github.com/supabase/postgrest-dart/blob/a1db368fc59d952a764dddeacd83061ab5f34595/lib/src/postgrest_builder.dart#L53).

And indeed, `method` on this line is a `String?` that is never initialised, which throws when calling `method!`. This could be solved by making `method` as `required` in `PostgrestBuilder`'s constructor or by putting a default value (like `"get"` for example), not sure what's best.

**Comment by thalkz** [comment]
Actually the issue is that you called `.execute()` directly on `from("servers")`. There is no query to execute. Try replacing
```
final response = await Supabase.client.from("public").execute();
```
with
```
final response = await Supabase.client.from("public").select().execute();
```

Still this is a bit confusing. It should either not be possible to call `execute()` directly, or it should return a more explicit error.

**Comment by phamhieu** [comment]
I implemented a fix [here](https://github.com/supabase/postgrest-dart/commit/5f6e140c53a2f61de5a7cba2fdbb6326ae3ee93a)

**Comment by carlomigueldy** [comment]
Thank you @thalkz @phamhieu! Will take a look now.

**Comment by carlomigueldy** [comment]
Will close the issue now.

If this https://github.com/supabase/postgrest-dart/commit/5f6e140c53a2f61de5a7cba2fdbb6326ae3ee93a gets merged then would also be great
