### ISSUE TITLE
Implementation `Column is in an array`

### ISSUE THREAD

**Issue by rickypid** [supabase/supabase-dart#172]
Hello everyone,

I would need to have a stream coming from a query with a `Column is in an array` filter

Can I propose a PR with this modification? Do you see there are some problems with this?

I think we need to implement other missing filters here (maybe not just `Column is in an array`):

https://github.com/supabase/supabase-dart/blob/717d751aa3828ffeb507de06a3d083555898b550/lib/src/supabase_stream_builder.dart#L319-L339

**Comment by Vinzent03** [comment]
I don't know exactly what filter you are searching for. Do you mean the [in](https://supabase.com/docs/reference/dart/in) operator? Either way the operators listed there should be all supported by the realtime server, so changing the client code can't fix this.

**Comment by rickypid** [comment]
For example I would need to get the stream of this query:

```dart
    Supabase.instance.client.from('countries')
        .stream(primaryKey: ['id'])
        .in_('column', [1,2,3]) //<==== unsupported filter
        .listen((List<Map<String, dynamic>> data) {
      // Do something awesome with the data
    });
```

**Comment by Vinzent03** [comment]
I'm going to close this for now, as there is nothing we can do on the client. See the [upstream issue](https://github.com/supabase/walrus/issues/9)
