### ISSUE TITLE
Support web

### ISSUE THREAD

**Issue by bdlukaa** [supabase/supabase-dart#18]
# Feature request

It'd be awesome to have web support for this package, so that I can use supabase on my Flutter Web project. That means the package can't import `dart:io` at any ways. Check https://pub.dev/packages/supabase/score

![](https://user-images.githubusercontent.com/45696119/116941320-d7e8a100-ac45-11eb-8382-15981181e904.png)

**Comment by agwanyaseen** [comment]
If it's supporting on web, then why on [pub](https://pub.dev/packages/supabase) it is marked as web supported.
It should be removed then.

![image](https://user-images.githubusercontent.com/37746694/119094304-7e96b500-ba2e-11eb-9774-1b4c75cc24f5.png)

**Comment by phamhieu** [comment]
Thanks to this PR https://github.com/supabase/storage-dart/pull/3

Supabase-dart already has web support.

**Comment by agwanyaseen** [comment]
Looks cool, Excited to try :)
