### ISSUE TITLE
Flutter - Realtime Subscription is not working

### ISSUE THREAD

**Issue by sunilmishra** [supabase/supabase-dart#19]
I have created sample flutter app where trying to subscribe realtime the changes on table `profiles`.
 
sample code:

 late RealtimeSubscription _subscription;

 void subscribeProfiles() {
    _subscription = client.from('profiles').on(SupabaseEventTypes.insert, (x) {
      print('on profiles.insert: ${x.table} ${x.eventType} ${x.oldRecord}');
    }).subscribe((String event, {String? errorMsg}) {
      print('event: $event error: $errorMsg');
    });
  }

  void disposeProfiles() {
    client.removeSubscription(_subscription);
  }

subscribeProfiles method is called on initState() at StatefulWidget.

here, client is supabase instance. Unable to see any print statement when trying to insert new profile in profile table. Profile table is recorded successfully. I have checked that on supabase  website. All other features like insert, delete, read are working perfectly.  Please let me know what am missing?

## System information
- OS: MacOS, IOS
- Flutter 2.0.6

**Comment by w3b6x9** [comment]
@sunilmishra realtime is turned off by default so i think that's why you're not receiving the changes.

run this on your db and try again:

```
begin; 
  -- remove the realtime publication
  drop publication if exists supabase_realtime; 

  -- re-create the publication but don't enable it for any tables
  create publication supabase_realtime;  
commit;

-- add a table to the publication
alter publication supabase_realtime add table profiles;
```

**Comment by w3b6x9** [comment]
@sunilmishra I'm going to close this issue. Feel free to reopen if realtime is still not working.

**Comment by sunilmishra** [comment]
Thank you @w3b6x9  for prompt reply. 
We can do the same using visual UI at https://app.supabase.io/project/XXXXXXXXXXXX/database/replication 
Click on `All Tables` or `0 Tables` at column Source.  It will allow us to enable `supabase_realtime` for all tables or selected table using switch button.
