### ISSUE TITLE
Access token not refreshing upon session recovery.

### ISSUE THREAD

**Issue by brycegoh** [supabase/supabase-dart#22]
# Bug report
Since its my first time posting an issue, I apologise if this is the wrong type of issue to bring up.

## Describe the bug
I have a self hosted Supabase using python. I am using flutter with Supabase-dart to use Supabase Auth. For every HTTP request to my self hosted Supabase server, I am attaching my access token to request Header using:
```dart
String getAccessToken() {
    final String accessToken =
        _supbaBaseClient.auth?.currentSession?.accessToken;
    return accessToken;
  }
```
I followed the example at [splash screen example](https://github.com/phamhieu/supabase-dart-demo/blob/main/lib/Screens/splash_screen.dart)
However, once I try to recover session using a locally stored session persist string, the access token is not getting refreshed and any subsequent HTTP request to my self hosted server, gets a 401 token has expired error.

```dart
// From source code:
final expiresAt = persistedData['expiresAt'] as int?;
final timeNow = (DateTime.now().millisecondsSinceEpoch / 1000).round();
 //after 1 hour, access token expires even thought session has been recovered, 
if (expiresAt < timeNow) { 
        if (autoRefreshToken && session.refreshToken != null) {
// refreshToken does not get invoked automatically on session recovery.
          final response =
              await _callRefreshToken(refreshToken: session.refreshToken);
          return response;
        } else {
          return GotrueSessionResponse(error: GotrueError('Session expired.'));
        }
      } else {
        _saveSession(session);
        return GotrueSessionResponse(data: session);
      }
```

>> EDIT: I have fixed it by calling `_supbaBaseClient.auth.refreshSession();` after `_supbaBaseClient.auth.recoverSession(persistSessionString);`
Is this suppose to be the way?

>> Not sure if I am correct but I suspect the access token is being automatically refreshed 1 min before expiry based on a timer whenever a session is saved. However, that produces a new session with the new access token which has a new persistent session string which is not stored locally. Therefore, after 1 hour, the access token does get refreshed but the locally stored persistent session string is not updated with the new refreshed access token and still contains the old expired access token. So upon session recovery using the persistent session string, the old expired access token is used?
If this is the case, how should I trigger local storage of the new persistent session string once the automatic refresh token function is invoked?

## To Reproduce
1. After successful sign in, store persistent session string.
2. Upon reload on application after 1 hour, invoke recoverSession.
3. recoverSession does not invoke refreshToken.
4. Any subsequent http request to self hosted supabase server is rejected due to expired access token.

Eg.
Upon recovering session after 1 hour, JWT token has already expired.
```dart
final response =
          await _supbaBaseClient.auth.recoverSession(sessionString);
        print("NEW ACCESS TOKEN: ${response.data.accessToken}"); // JWT was not refreshed and has expired
```

## Expected behavior
Shouldn't access token be refreshed upon session recovery?
In recoverSession, `(expiresAt < timeNow)` always return false?
I am trying to get a new access token after session recovery to attach to HTTP requests to self hosted supabase server.

## System information
Running flutter app in debug mode in macOS.
Using Dio for HTTP requests and flutter_secure_storage to store session persist string.

**Comment by phamhieu** [comment]
Hi @brycegoh, this bug has been fixed on the latest version https://pub.dev/packages/supabase. Let me know if you are still facing the issue. 

Also, I updated [supabase flutter demo](https://github.com/phamhieu/supabase-dart-demo) app recently. Along with using splash screen to handle recover session when app exists. You can listen to lifecycle state in order to [recover session on app resume](https://github.com/phamhieu/supabase-dart-demo/blob/main/lib/components/lifecycle_state.dart).

**Comment by Mohamed50** [comment]
i still get the same issue

**Comment by bdlukaa** [comment]
@Mohamed50 can you reproduce it on the latest prerelease? https://pub.dev/packages/supabase/versions/1.0.0-dev.2
