### ISSUE TITLE
Flutter Web gives Error: UnimplementedError with File f = new File('example.txt');

### ISSUE THREAD

**Issue by ExzaSolutions** [supabase/supabase-dart#23]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by phamhieu** [comment]
Hi @ExzaSolutions, `dart:io` doesn't support flutter web. You need to use https://pub.dev/packages/universal_io instead.
