### ISSUE TITLE
Add public download url of the asset in StorageResponse

### ISSUE THREAD

**Issue by paurakhsharma** [supabase/supabase-dart#25]
First of all, Thank you for this amazing project.

# Feature request

- Add an option to get the public download URL for the uploaded asset just like firebase storage.

## Is your feature request related to a problem? Please describe.

- Currently, when I upload the asset to my storage I need to save the relative path of the asset in the database and download the file when I need to show it in the Flutter app.
- This is a problem especially when I need to show an image to a user as I cannot directly use it as a Network Image.

## Describe the solution you'd like

- Ability to get the public URL of the file (**just like the one I can copy from the storage console**) from the upload response.

## Describe alternatives you've considered

Currently, I use a future builder to download the image and show it to the user.
```dart
Future<dynamic> downloadImage(String imagePath) {
    return _client.storage.from('journalImages').download(imagePath);
  }
```

```dart
FutureBuilder(
      future: downloadImage(imagePath),
      builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
        if (!snapshot.hasData)
          return Center(
            child: CircularProgressIndicator(),
          );

        return Image.memory(
          snapshot.data.data,
          height: height,
        );
      },
    )
```

## Additional context

- If this feature is lacking in the Supabase itself, I can move this issue to Supabase project.

**Comment by dshukertjr** [comment]
Thanks @paurakhsharma for opening an issue!

Method to get public URL landed on supabase-js recently. 
https://github.com/supabase/storage-js/pull/10

I can try to get this implemented this weekend!

**Comment by paurakhsharma** [comment]
@dshukertjr That sounds awesome. Looking forward to it 😍

**Comment by phamhieu** [comment]
@paurakhsharma, you can find the new public url feature on the latest version https://pub.dev/packages/supabase

**Comment by paurakhsharma** [comment]
@dshukertjr @phamhieu 
I am having some problem getting it to work, maybe I am missing something here:

Here is my code to get the `publicUrl`

```dart
Future<String?> uploadImage(PlatformFile file) async {
    final fileName = '${DateTime.now().toString()}_${file.name}';
    final response = await _client.storage.from('journalImages').upload(
          fileName,
          File(file.path!),
        );

    if (response.data == null) return null;
    final downloadUrl =
        _client.storage.from('journalImages').getPublicUrl(fileName).data;

    print(downloadUrl);

    return downloadUrl;
```

This the the URL that gets printed out: https://dlrvdojpksbdmvnygpeb.supabase.co/storage/v1/object/public/journalImages/2021-06-22%2007:58:17.902992_IMG_0005.jpeg

But it returns 404.

Anything I am missing?

**Comment by phamhieu** [comment]
@paurakhsharma can you check on your supabase project dashboard if `journalImages` is a public bucket?

the generated url looks valid to me.

maybe you can try to rename your folder to use `Only lowercase letters `
<img width="581" alt="Screenshot 2021-06-22 at 9 26 20 AM" src="https://user-images.githubusercontent.com/689843/122853098-e9902000-d33b-11eb-973b-a5dc6ef33f67.png">

**Comment by dshukertjr** [comment]
Hey @paurakhsharma !

By default all buckets created in Supabase are private. You can go into your Supabase console's storage setting and make buckets public!

**Comment by paurakhsharma** [comment]
Thanks, @dshukertjr, and @phamhieu for the quick response.
Yes, my bucket wasn't set to public. Setting it to public worked like a charm 🚀 

Many thanks.
