### ISSUE TITLE
Storage - Unable to upload image to private bucket 

### ISSUE THREAD

**Issue by sunilmishra** [supabase/supabase-dart#26]
## Describe the bug

Unable to upload image file to private bucket using flutter in IOS.

Following error is showing :
- new row violates row-level security policy for table "objects"

Please suggest what am i missing. I tried to with suggested template policies on website also but still unable to upload.

**Comment by phamhieu** [comment]
Hi @sunilmishra, can you upload your bucket policies for reference. I guess that you don't provide read access for `objects`. After inserting, it fails to retrieve the data to return and throws error.

<img width="1041" alt="Screenshot 2021-06-21 at 7 39 16 AM" src="https://user-images.githubusercontent.com/689843/122693440-153fd700-d264-11eb-851b-33210e2b42a7.png">

**Comment by sunilmishra** [comment]
@phamhieu Thank you! Issue resolved.
