### ISSUE TITLE
Documentation on how to keep the user logged in

### ISSUE THREAD

**Issue by bdlukaa** [supabase/supabase-dart#27]
# Improve documentation

## Describe the problem

Currently, there's no documentation on how to keep the user logged in after the application is closed and opened again. The user have to log in again.

## Describe the improvement

Improve the documentation on how to keep the user logged in. This is something that is done automatically on the js library, but not on this one.

## Additional context

This will likely be used on Dart Web Apps and Flutter Apps to provide a good user experience.

**Comment by bdlukaa** [comment]
I could get this working on Flutter using the `shared_preferences` plugin:

```dart
/// Persist the current user session. This method should be called when
/// the user log in into the app.
Future<void> _persistSession(Session session) {
  print('Persisting session string');
  return sharedPreferences.setString( //This is the shared preferences instance
    supabaseSessionKey,
    session.persistSessionString,
  );
}

/// Recover the previous user session, if any.
///
/// This method should be used on the main function, before `runApp`
Future<bool> recoverSession() async {
  // TODO: Use secure storage instead of shared preferences
  if (sharedPreferences.containsKey(supabaseSessionKey)) {
    print('Found persisted session string, attempting to recover session');
    final jsonStr = sharedPreferences.getString(supabaseSessionKey)!;
    final response = await client.auth.recoverSession(jsonStr);
    if (response.error == null) {
      print('Session successfully recovered for user ID: ${response.user!.id}');
      _persistSession(response.data!);
      return true;
    }
  }
  return false;
}
```

**Comment by phamhieu** [comment]
Hi @bdlukaa, thanks for your code example. To be better, you can listen to app lifecycle to support recovering session on app resumes.

You can take a look at the example [here](https://github.com/phamhieu/supabase-dart-demo/blob/main/lib/components/lifecycle_state.dart)

> Improve the documentation on how to keep the user logged in. This is something that is done automatically on the js library, but not on this one.

We will create a Supabase flutter library to support this feature. Stay tuned for further updates.

**Comment by Vinzent03** [comment]
Since I see that the flutter package is released, I see it's implemented with SharedPreferences, but is this really secure?

**Comment by bdlukaa** [comment]
I don't think so.

**Comment by bdlukaa** [comment]
I don't think so. [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) can be used for Android, iOS and Linux.

**Comment by phamhieu** [comment]
Hi @Vinzent03 @bdlukaa, originally we choose SharedPreferences cos it's easy to use and it also supports flutter web.

Thanks for the suggestion @bdlukaa, we will look into it and update you as soon as possible.

**Comment by phamhieu** [comment]
Hi @Vinzent03 @bdlukaa, now you can use any plugin to persist user session with [Custom Localstorage](https://github.com/supabase/supabase-flutter#custom-localstorage)
