### ISSUE TITLE
Google Login Error in Flutter mobile app

### ISSUE THREAD

**Issue by muhammadmateen027** [supabase/supabase-dart#29]
# Bug report

## Google Login Error in Flutter mobile app

I have tried to log in using google `..signIn(provider: Provider.google)`, but it doesn't help at all. Webview pop-up doesn't appear even you can get the URL in `print()` method.

## To Reproduce

1. Setup [google login](https://supabase.io/docs/guides/auth/auth-google) as per your documentation
2. Add button action in the app to login (I tried on physical device and simulator)
3. No pop-up to show available accounts
4. If you try to print `URL` from `Result`, it shows a URL like this `https://[YOUR_APP_ID].supabase.co/auth/v1/authorize?provider=google`

## Expected behavior

The user should be able to view available google accounts and select.

## Screenshots

No screenshot because nothing available on the page but I can share code snippets. 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/24449076/123509673-665b2b00-d6a9-11eb-94c8-f264b982a634.png">

## System information

- OS: `macOS, Android device. Android Simulator`
- Version of supabase-Flutter: `supabase: ^0.0.1-dev.22`

**Comment by nomanmurtaza786** [comment]
I am getting same problem. Anyone can share the flutter example, please.

**Comment by phamhieu** [comment]
Hi @muhammadmateen027 @nomanmurtaza786 

`supabase-dart` package just returns the authorize url for third party providers. You will need to manually trigger the browser tab to open this url.

you can take a look at the code example [here](https://github.com/supabase/supabase/discussions/1885#discussioncomment-855633)

**Comment by phamhieu** [comment]
@muhammadmateen027 we release supabase_flutter to help with deeplink authentication on mobile. Give it a try and let me know if you are still facing the problem with Google login https://pub.dev/packages/supabase_flutter

**Comment by Sahil-kachhap** [comment]
@phamhieu I was trying to implement google authentication. As per the documentation, we require a google client id and a client secret. But after following those steps I am just getting a client id (no client secret, I have got a JSON file though but it too does not have anything sort of secrets). Seems like google client secrets have been deprecated for native applications. Can you suggest anything on how to proceed from here on now?

**Comment by dshukertjr** [comment]
@Sahil-kachhap It appears that you have selected Android application in your case, but at the moment, you need to create a OAuth 2.0 Client IDs for web application even for native apps using Flutter. Don't worry, you will be able to sign users in form your iOS and Android apps even if you create a web application OAuth 2.0 Client ID. If you choose web application, it will give you all the necessary information including client secret!
