### ISSUE TITLE
Pagination 

### ISSUE THREAD

**Issue by nomanmurtaza786** [supabase/supabase-dart#31]
Hi, I am trying to implement pagination in flutter via this guide https://github.com/supabase/supabase/discussions/1223#discussioncomment-641447 

But I can't find the count function in the Dart client. Do you know, how can we implement pagination with a dart. Want to count total rows.

**Comment by phamhieu** [comment]
👋 @nomanmurtaza786, you can pass CountOption param into execute() method to receive the count value.

```dart
final res = await supabase
    .from("cars")
    .select("*", { count: "exact" })
    .order("id", { ascending: true })
    .range(from, to)
    .execute(count: CountOption.exact);
print(res.count)
```

**Comment by nomanmurtaza786** [comment]
> ```dart
> execute(count: CountOption.exact)
> ```
Getting this problem 
Undefined name 'CountOption'.
Try correcting the name to one that is defined, or defining the name.

![image](https://user-images.githubusercontent.com/14288484/124056958-01695180-da6a-11eb-9b24-d5e2312ce2dc.png)

**Comment by phamhieu** [comment]
Can you try again with the latest `supabase-dart` client. I pushed a hotfix for this issue.

**Comment by nomanmurtaza786** [comment]
> Can you try again with the latest `supabase-dart` client. I pushed a hotfix for this issue.

Thanks working
