### ISSUE TITLE
Program won't exit

### ISSUE THREAD

**Issue by GZGavinZhao** [supabase/supabase-dart#34]
# Bug report

## Describe the bug

Program won't exit after account login (other behaviors, such as file upload, have not been tested).

## To Reproduce

```dart
import 'package:supabase/supabase.dart';

void main(List<String> arguments) async {
  final client = SupabaseClient(url, key); // Put url and key here

  print('Logging in...');

  final login = await client.auth.signIn(
    email: 'email',
    password: '12345',
  );

  if (login.error == null) {
    print('Logged in, uid: ${login.data!.user!.id}');
  } else {
    print('Error!');
  }
}
```

## Expected behavior

It should output `logged in, uid: <some id>` or `Error!".

## Actual behavior

After outputting "logged in" and the id, the program just doesn't exit with no more logs.
```
Logging in...
Logged in, uid: 8ee21112-d3df-4cb3-b54c-c8326ab11b57

```
It will remain in this state forever.

## System information

- OS: Linux, Windows (both tested)
- Version: 0.0.1

## Additional notes

Is this an expected behavior? If this is a bug, it probably went un-noticed because in Flutter we wouldn't know (and don't care) if the program terminated or not. However, for a CLI, this problem would immediately show up.

**Comment by phamhieu** [comment]
> It will remain in this state forever.

Hi @GZGavinZhao, I'm not sure what do you want to archive. The code result seems correct to me.

**Comment by GZGavinZhao** [comment]
Sorry I was being unclear. My point is, say you're in a terminal. The expected behavior should be something this: 
```terminal
$ dart run
Logging in...
Logged in, uid: 8ee21112-d3df-4cb3-b54c-c8326ab11b57
Got some data...
$
```
The program ends and you can execute something else now. However, what happens to me is:
```terminal
$ dart run
Logging in...
Logged in, uid: 8ee21112-d3df-4cb3-b54c-c8326ab11b57
Got some data...
     <- cursor blinking here
```
The program just keeps running, even though every process is finished.

**Comment by phamhieu** [comment]
Thanks @GZGavinZhao, can you try again with `supabase-dart` latest version. You will also need to add this to the end of your code block
```
await client.auth.signOut();
print('Logged out');
```

As default, `supabase-dart` will manage user session and auto refresh it. So the thread will not exit until a user logout. Let me know if you are still facing the problem with latest version.

**Comment by GZGavinZhao** [comment]
@phamhieu Yes this resolves the problem. Thank you for the help! We should probably add this info somewhere in our docs, in case other people get stuck on this.
