### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bernaferrari** [supabase/supabase-dart#35]
I'm trying to learn supabase and this is my feedback:

- In the [README](https://github.com/supabase/supabase-dart#database), clicking in Database/Authentication/Storage takes me to Supabase docs. I want a link to storage-dart/postgrest-dart/etc. They contain additional samples in their README which I found helpful.

- There is no realtime mention in the README.

- There is no explanation why `response` has data but data is dynamic. When calling select.get(), it seems to always be an array. Documentation could mention its possible types.

**Comment by dshukertjr** [comment]
Hi @bernaferrari !

Thank you for your feedback! I will update the `README.md` with your suggestions. 

One thing, the reason why `data` is `dynamic` is because it could also be a `Map` in a case like this:
```dart
final res = await supabase
    .from('videos')
    .select()
    .eq('id', videoId)
    .single()
    .execute();

final data = res.data; // This is a Map
```

**Comment by bernaferrari** [comment]
You could write somewhere this example, like... Ok, so it can either be a Map or List (miss TypeScript so much). I got confused like... dynamic can be anything, will it be an integer someday? Now I know it won't.

My main issue with supabase is that I don't know how to go from one place to the other in the documentation. Some things are there, but everything is disconnected, I need to Google a lot. Thanks.

**Comment by dshukertjr** [comment]
Hey @bernaferrari, thanks for the quick reply.

>You could write somewhere this example, like... Ok, so it can either be a Map or List (miss TypeScript so much). I got confused like... dynamic can be anything, will it be an integer someday? Now I know it won't.

Maybe this is something we can mention in the comments within the code. 

>My main issue with supabase is that I don't know how to go from one place to the other in the documentation. Some things are there, but everything is disconnected, I need to Google a lot. Thanks.

Are you referring to [the official documentation](https://supabase.io/docs), or dart specific documentation here? Generally, the Dart library should be very similar to the JavaScript library, but I'm curious to hear what part you were having trouble finding solutions.

**Comment by bernaferrari** [comment]
Dart only. I'm trying to do the basics on Dart and it is been hard (not impossible, just hard).
I didn't see the JS :(

**Comment by dshukertjr** [comment]
Thanks for the clarification! 

Maybe I an include a sentence somewhere within the readme to direct developers arriving here to the JavaScript references. Would you say that would solve the current problem?

**Comment by bernaferrari** [comment]
Saying it came from JS wouldn't help. I think if you can take a screenshot of a method from JS and Dart and show why it is better in JS but same in Dart could be veeery helpful. You would make me visit the JS page then.

**Comment by dshukertjr** [comment]
Having some kind of screenshot might be great for amazing developer experience. Will consider it for future improvements!

For now, I will include a link to the official Supabase documentation kind of like how [supabase-js](https://github.com/supabase/supabase-js) does it. This way, developers should know where to go to look at documentations!
