### ISSUE TITLE
Ability to generate CUID an alternative to UUID

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/supabase-dart#37]
# Feature request
Ability to generate CUID via Supabase Package using
`Supabase.generateCUID();`

## Is your feature request related to a problem? Please describe.
CUID has a several benefits compare to Auto Incremented IDs and UUID. One of the benefits is 
> Collision-resistant ids optimized for horizontal scaling and binary search lookup performance.

We can look more here at https://github.com/ericelliott/cuid

**Comment by bdlukaa** [comment]
This issue should be raised in the main supabase repository
