### ISSUE TITLE
stream doesn't update realtime

### ISSUE THREAD

**Issue by akram-95** [supabase/supabase-dart#41]
# Bug report

## Describe the bug
using stream will my UI just update when i add new value but when i delete value, it will not update

**Comment by StevePhuc** [comment]
I have the same issue. when insert, new row is insert but the stream is not update
The code I using:

```
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class ChatScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder(
        stream: Supabase.instance.client
            .from('chat')
            .stream()
            .order('id')
            .limit(30)
            .execute(),
        builder: (ctx, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
          final data = snapshot.data! as List;
          print(data);
          return ListView.builder(
            itemCount: data.length,
            itemBuilder: (ctx, index) => Container(
              padding: EdgeInsets.all(8),
              child: Text('${data[index]['id']} ${data[index]['message']}'),
            ),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          final insertResponse =
              await Supabase.instance.client.from('chat').insert([
            {'message': 'new message'}
          ]).execute();
          if (insertResponse.error == null) {
            print('insertResponse.data: ${insertResponse.data}');
          }
        },
      ),
    );
  }
}

```

already allow realtime for that table
```
begin; 
  -- remove the realtime publication
  drop publication if exists supabase_realtime; 

  -- re-create the publication but don't enable it for any tables
  create publication supabase_realtime;  
commit;

-- add a table to the publication 
alter publication supabase_realtime add table chat;

```

![image](https://user-images.githubusercontent.com/27769175/129665823-66883588-b6b3-4932-853a-4a02e11b033e.png)

**Comment by dshukertjr** [comment]
Thanks @akram-95 for opening this issue and @StevePhuc for also adding more context!

Could you confirm that you have `update` and `delete` realtime events turned on in the Supabase console? 

https://app.supabase.io/project/[YOUR_PROJECT_ID]/database/replication

<img width="1380" alt="Screen Shot 2021-08-17 at 14 36 06" src="https://user-images.githubusercontent.com/18113850/129669376-3afb64d5-6dd2-4ca1-a0cc-5ef180a326f4.png">

**Comment by akram-95** [comment]
Hello @dshukertjr  , yeah o confirm that I enabled all real time functions

**Comment by dshukertjr** [comment]
@akram-95 
Thanks for confirming. Did you enable realtime via Supabase console or though running your own SQL? 

If you used your own SQL, could you ensure if [full replication](https://supabase.io/docs/reference/javascript/subscribe#listening-to-deletes) is enabled?
```sql
alter table "your_table" replica identity full;
```

Also, would it be possible for you to share the scheme of the table you are using? With it, I might be able to reproduce it on my end!

**Comment by dshukertjr** [comment]
@akram-95 
Sorry, please ignore the previous message that you received in your email inbox. 

Could you share the scheme of the table at which you are trying to listen to as stream?

**Comment by StevePhuc** [comment]
after update sql with `alter table chat replica identity full;` it work now. Thanks @dshukertjr 
 

```
begin; 
  -- remove the realtime publication
  drop publication if exists supabase_realtime; 

  -- re-create the publication but don't enable it for any tables
  create publication supabase_realtime;  
commit;

-- add a table to the publication
alter publication supabase_realtime add table chat;

alter table chat replica identity full;
```

**Comment by dshukertjr** [comment]
@StevePhuc 
I'm glad you were able to fix it. I took down my previous post, because I thought that might not have been the issue, but I guess it was!

**Comment by dshukertjr** [comment]
@StevePhuc 
Weird is thing is that I actually do not have `identity` set to `full`, and yet am able to receive updates and deletes. 

When I run 
```sql
SELECT CASE relreplident
          WHEN 'd' THEN 'default'
          WHEN 'n' THEN 'nothing'
          WHEN 'f' THEN 'full'
          WHEN 'i' THEN 'index'
       END AS replica_identity
FROM pg_class
WHERE oid = 'mytablename'::regclass;
```

I get `default`.  Could you maybe try to run the above SQL command to see what you get for tables that you haven't set to `full` yet?

**Comment by StevePhuc** [comment]
`Could you maybe try to run the above SQL command to see what you get for tables that you haven't set to full yet?`

![image](https://user-images.githubusercontent.com/27769175/129695964-3e3f1138-a0ac-424e-ad51-17d955666b5f.png)

**Comment by akram-95** [comment]
@dshukertjr 
Did you mean that ? 
![Uploading 129698218...]
![Uploading 129698233...]

**Comment by akram-95** [comment]
@dshukertjr 
Did you mean that ? 
![image](https://user-images.githubusercontent.com/55693316/129698584-be5ad714-63d5-4ce7-932b-65c0ea68266c.jpeg)

![image](https://user-images.githubusercontent.com/55693316/129698623-1ff756ab-2a8b-4443-be32-2b72d2457c3c.jpeg)

**Comment by akram-95** [comment]
> @StevePhuc 
> 
> I'm glad you were able to fix it. I took down my previous post, because I thought that might not have been the issue, but I guess it was! 
> 
> 
> 
> @akram-95 Could you also try running?
> 
> ```sql
> 
> alter table your_table_name replica identity full;
> 
> ```

When I did run it , I did get no rows gets

**Comment by akram-95** [comment]
@StevePhuc 
How did you solve the problem?

**Comment by dshukertjr** [comment]
@akram-95 
Sorry, for not being clear. Could you show me your table definition? 
If you created your table with SQL, then the SQL code would be better, but if you have created from Supabase's console, then a screenshot is okay. Also if you could let me know which column is the primary key, that would be great. 
<img width="967" alt="Screen Shot 2021-08-17 at 19 49 33" src="https://user-images.githubusercontent.com/18113850/129713256-0045b600-cf3d-40ac-8d2a-edd34ed842e9.png">


@StevePhuc 
I was further investigating this issue, and it seems like there is a bug where `stream()` should not work when replica identity is set to `full`. If it's possible, could you share the SQL you used to create your `chat` table? 

For me, it's working when replica identity is set to `default`.

**Comment by akram-95** [comment]
> @akram-95 
> 
> Sorry, for not being clear. Could you show me your table definition? 
> 
> If you created your table with SQL, then the SQL code would be better, but if you have created from Supabase's console, then a screenshot is okay. Also if you could let me know which column is the primary key, that would be great. 
> 
> <img width="967" alt="Screen Shot 2021-08-17 at 19 49 33" src="https://user-images.githubusercontent.com/18113850/129713256-0045b600-cf3d-40ac-8d2a-edd34ed842e9.png">
> 
> 
> 
> 
> 
> @StevePhuc 
> 
> Thank you so much for sharing your result! 
> 
> I was further investigating this issue, and it seems like there is a bug where `stream()` should not work when replica identity is set to `full`. If it's possible, could you share the SQL you used to create your `chat` table? 
> 
> 
> 
> For me, it's working when replica identity is set to `default`. 

I did create my table from the console 
And here the table definition 

![image](https://user-images.githubusercontent.com/55693316/129716222-f1ad3ca8-73fd-4bdd-8b44-d2f1e9dddffd.jpeg)

**Comment by dshukertjr** [comment]
@akram-95 
I can see that you have an `id` property, but couldn't really tell the rest. You can take a screenshot by pressing command + Shift + 4 on mac!

Anyway, let me start over. I did create a brand new Supabase project, and was able to receive all `Insert`, `Update`, and `Delete` events with the following steps. Please follow these steps and let me know if they work. It's simple. No need to tweek the replication identity settings or anything. 

1. Go to `Database`>`Replication` and check everything . 
<img width="1377" alt="Screen Shot 2021-08-17 at 20 26 18" src="https://user-images.githubusercontent.com/18113850/129718113-00f1c803-69df-4beb-9b60-157295abd794.png">
2. Click the button inside the red square
<img width="1377" alt="Screen Shot 2021-08-17 at 20 26 18" src="https://user-images.githubusercontent.com/18113850/129718253-0d505496-162d-44d6-845b-de5ccd5434f0.png">

3. Check that the table at which you want to listen to realtime events are turned on. If not, turn it on. 
<img width="1325" alt="Screen Shot 2021-08-17 at 20 28 49" src="https://user-images.githubusercontent.com/18113850/129718287-90dba7c9-cb7e-4685-be75-a6127baac388.png">

4. Listen to the data using a simple `StreamBuilder`
```dart
StreamBuilder<List<Map<String, dynamic>>>(
  stream: supabase.from('chats').stream().order('id').limit(30).execute(),
  builder: (context, snapshot) {
    if (snapshot.hasError) {
      return Center(child: Text(snapshot.error.toString()));
    }
    if (snapshot.connectionState == ConnectionState.active) {
      final dataList = snapshot.data!;
      return ListView.builder(
        itemCount: dataList.length,
        itemBuilder: (context, index) {
          final data = dataList[index];
          return ListTile(
            title: Text(data['text']),
          );
        },
      );
    } else {
      return Container();
    }
  },
)
```

**Comment by akram-95** [comment]
@dshukertjr I did make it exactly how you told me 
It doesn't update the ui 
Here is a video of that https://user-images.githubusercontent.com/55693316/129722286-0e1e3581-f460-4d2d-ad8f-11921457178e.MOV

**Comment by dshukertjr** [comment]
@akram-95 

Thanks for sharing a video. 
Okay, in that case, could you make sure that you have primary key for your table? When you create a table, you need to have this check box checked. 
<img width="1364" alt="Screen Shot 2021-08-17 at 21 04 58" src="https://user-images.githubusercontent.com/18113850/129722585-c75a1e6c-a2ad-4a90-88eb-bc4c1184c326.png">

Also, do you have a public repo that I can take a look at where your working code is stored?

**Comment by akram-95** [comment]
@dshukertjr 
It works now , I could know how to solve it 
When we create a table and than enable the real-time , it doesn't work perfectly 
I needed to delete it and enable real-time and than create the table and it works now perfect 
I wanted to share that with you , maybe it can help you to understand the behaviour better 

Now I have another issue , I get this error when I use nested Streambuilder ![image](https://user-images.githubusercontent.com/55693316/129728546-4cd16460-15a4-4b61-8399-0b9fa9018831.jpeg)

**Comment by dshukertjr** [comment]
@akram-95 
So glad to hear that it is working now. Thanks for sharing the steps you took to make it work. We will work on improving the documentation on how to get started with it. 

Thanks for reporting the issue with nested `StreamBuilder`. Could you actually open another issue for that one?
