### ISSUE TITLE
bug with nested Streambuilder

### ISSUE THREAD

**Issue by akram-95** [supabase/supabase-dart#42]
# Bug report
hello, 
i get this issue when i use nested Streambuilder

![](https://user-images.githubusercontent.com/55693316/129728546-4cd16460-15a4-4b61-8399-0b9fa9018831.jpeg)

does anyone know how to solve this issue?

**Comment by bdlukaa** [comment]
How does your code look like?

**Comment by akram-95** [comment]
Hey @bdlukaa 

Ok I show a screenshot of it
![image](https://user-images.githubusercontent.com/55693316/129810655-bbe1b75a-adaf-454d-8c45-ca68cf09f740.jpeg)

**Comment by bdlukaa** [comment]
hmm. it's probably because it's inside of a ListView.builder

**Comment by akram-95** [comment]
@bdlukaa 
Ok , there is another possibility to make it work ? 
I'm new using supabase , I was using Firebase, it wasn't a problem to do nested Streambuilder With listview

**Comment by bdlukaa** [comment]
@dshukertjr should we remove the `.close()` call when there's no listeners?

StreamController should not be a memory issue.

**Comment by dshukertjr** [comment]
@bdlukaa 
Yeah, that makes sense. Great point. Let's do that!

**Comment by akram-95** [comment]
> @bdlukaa 
> 
> Yeah, that makes sense. Great point. Let's do that! 

@dshukertjr @bdlukaa 

I hope that will solve the issue 
Thank you fir your support guys 🙏

**Comment by dshukertjr** [comment]
@akram-95 
This issue should be fixed with the latest release of `supabase` and `supabase_flutter` package! Thanks for the patients!

**Comment by akram-95** [comment]
@dshukertjr That sounds great 
I will try it , thank you 🙏
