### ISSUE TITLE
Interrupt the connection with supabase

### ISSUE THREAD

**Issue by akram-95** [supabase/supabase-dart#48]
I get this exception VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 61, address = eorvfftziolcmktbcetw.supabase.co, port = 49429 and  then I can't fetch data more from supabase and I can't open my console on supabase also

**Comment by bdlukaa** [comment]
Is this still happening?

**Comment by akram-95** [comment]
No , it happens so often

**Comment by phamhieu** [comment]
Hi @akram-95 can you send email to support@supabase.io with your project and fetch query info. We can take a look at the db instance.
