### ISSUE TITLE
Enable branch protection rule

### ISSUE THREAD

**Issue by phamhieu** [supabase/supabase-dart#49]
# Chore

## Describe the chore

I will enable [branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) on all dart/flutter repos.

In the future, we can’t merge code directly into the repo. Need to create PR and at least 1 approval review in order to merge.

FYI: @bdlukaa @dshukertjr. Let me know if you are ok with it. Thank you.

**Comment by dshukertjr** [comment]
Love it!

**Comment by bdlukaa** [comment]
Sounds good to me
