### ISSUE TITLE
Authentication with social media

### ISSUE THREAD

**Issue by akram-95** [supabase/supabase-dart#52]
I'm using supabase as a backend and I'm so happy to use but I want to implement authentication with social media. 
Can you please implement this feature? 
It would be great

**Comment by dshukertjr** [comment]
Hi @akram-95 !

You can actually sign users in via social account today!

You can follow the steps [here](https://github.com/supabase/supabase-flutter#supabase-3rd-party-logins-config) to implement deeplink. Then you can use the [`auth.signInWithProvider()`](https://supabase.io/docs/reference/dart/auth-signinwithprovider) method available on [supabase_flutter](https://pub.dev/packages/supabase_flutter) to sign your users in.

**Comment by akram-95** [comment]
@dshukertjr , but how can I use this method if I'm already using Supabase-dart?

**Comment by dshukertjr** [comment]
@akram-95 

You could start using `supabase_flutter`! 
`supabase_flutter` contains everything that `supabase_dart` contains, so migration should not be that hard!

**Comment by akram-95** [comment]
Yeah but the point supabase_flutter doesn't yet support null safety

**Comment by dshukertjr** [comment]
@akram-95 
`supabase_flutter` does support null safety. You can read more about it [here](https://github.com/supabase/supabase-flutter/issues/18#issuecomment-907589357), but `supabase_flutter` not having the `null-safety` badge on pub.dev is just a bug on Flutter and index.db! You can safely and confidently migrate to `supabase_flutter`!

**Comment by akram-95** [comment]
@dshukertjr Ok thanks
