### ISSUE TITLE
Deleting User from Authentication in dart

### ISSUE THREAD

**Issue by julius-stuemmler** [supabase/supabase-dart#58]
# Bug report
Hey guys, maybe I simply didn't found it, but I want to implement a simple function to delete a user from the supabase authentication. I found [this](https://supabase.io/docs/reference/javascript/delete-user)  for js, but in Flutter I don't get this option.
I can use `client.auth.api`, but the delete function is missing.

dependencies: 
flutter: 2.5.3
dart:  2.14.4
supabase: ^0.2.8

**Comment by bit-burger** [comment]
You should not be using this in flutter anyway, its for a server

**Comment by dshukertjr** [comment]
@julius-stuemmler 
As @bit-burger has said, [`deleteUser()`](https://supabase.com/docs/reference/javascript/auth-api-deleteuser) method requires `service_role`, and therefore needs to be called from a server.

**Comment by Myzel394** [comment]
> @julius-stuemmler As @bit-burger has said, [`deleteUser()`](https://supabase.com/docs/reference/javascript/auth-api-deleteuser) method requires `service_role`, and therefore needs to be called from a server.

How do you call it from the server? Can you give a short example on how to delete users using Flutter?
