### ISSUE TITLE
Change errorMsg parameter in SubscriptionCallback to a positional argument

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase-dart#7]
# Feature request

## Is your feature request related to a problem? Please describe.

Thanks for creating and maintaining supabase-dart! I am enjoying creating flutter apps with it! 

This is just an opinion that I have, but I find the format of `SubscriptionCallback` a bit hard to work with. It might be easier if the `errorMsg` was an optional positional argument instead. 

current:
```
typedef SubscribeCallback = void Function(String event, {String errorMsg});
```

my suggestion:
```
typedef SubscribeCallback = void Function(String event, [String errorMsg]);
```

I know this would be a breaking change if introduced, so I am not sure when and how it should be introduced if it would be introduced at all, but it would be greatly appreciated if the team could receive this as a feedback from a single Supabase fan!

**Comment by dshukertjr** [comment]
Wow, great title huh? lol

**Comment by phamhieu** [comment]
Hi @dshukertjr, can you give more explanation for this quote
> but I find the format of SubscriptionCallback a bit hard to work with. It might be easier if the errorMsg was an optional positional argument instead.

To me, the code is the same. Just a different between `{}` and `[]`

**Comment by dshukertjr** [comment]
Hi @phamhieu !

Yeah, sure! It might be a teeny-tiny difference, but with the current code using {}, this is how you would write SubscriptionCallback. 

```
supabase
    .from('chats')
    .on(SupabaseEventTypes.all, (payload) {
  // Do something here
}).subscribe((event, {errorMsg}) {
  // Do something here
});
```

This has two limitations:
- You have to wrap `errorMsg` with {}
- You cannot change the variable name from `errorMsg` to something else

If we change the {} to [], we can get rid of both of the two restrictions and write it like this:

```
supabase
    .from('chats')
    .on(SupabaseEventTypes.all, (payload) {
  // Do something here
}).subscribe((event, errorMessage) {
  // `errorMsg` can be different variable name
  // Do something here
});
```

I know this is a very niche thing that I am pointing out, and is probably not the thing that should concern you, but is just my thoughts. 

Thanks for all the amazing work! I love the Supabase dart client! 

I am in the process of creating a sample app using flutter and Supabase, and was wondering if it would be okay for me to drop off feedback like this if I come across any?, or is there a better place for feedback like this other than Github issues?

**Comment by phamhieu** [comment]
> 1. You have to wrap errorMsg with {}
but with the other way, you still have to wrap it with []. Correct me if i'm wrong. You can submit a PR.

> 2. You cannot change the variable name from errorMsg to something else
This' true.

**Comment by phamhieu** [comment]
> and was wondering if it would be okay for me to drop off feedback like this if I come across any?

Yes, please do so. Thank you so much.

**Comment by dshukertjr** [comment]
> but with the other way, you still have to wrap it with []. Correct me if i'm wrong. You can submit a PR as reference.
You are absolutely right and I was absolutely wrong. Thank you for correcting me.
