### ISSUE TITLE
Making multiple subscriptions on the same client gets immediately CLOSED with error null

### ISSUE THREAD

**Issue by happy-san** [supabase/supabase-dart#8]
# Bug report

## Describe the bug

I have created a table `countries` with a single field `name`. In the following gist, when I comment out either `_subOnCountriesDelete`  or `_subOnCountriesInsert`, everything works as intended and I receive events during the 10 seconds. But when I don't comment out anything in the gist, both the subscriptions just return `event: CLOSED error: null`.

## To Reproduce

[This gist](https://gist.github.com/happy-san/f389c7836c31f6ab6ff886a5b3ddfd77)

## Expected behavior

The expected behavior is that the subscription should only end when `removeSubscription()` is called.

## System information

- OS: EndlessOS
- Version of supabase-dart: "0.0.1-dev.8"

## Additional context

[this](https://github.com/supabase/supabase/discussions/777#discussioncomment-413833)

**Comment by happy-san** [comment]
I've noticed that everything works fine with only one subscription in this [flutter example](https://github.com/happy-san/todo_supabase/blob/dev/lib/main.dart) too.

Maybe having multiple subscriptions on the same table is causing this issue.

**Comment by phamhieu** [comment]
Hi @happy-san, you can only have 1 active subscription per unique topic at any given time.

> While the client may join any number of topics on any number of channels, the client may only hold a single subscription for each unique topic at any given time. When attempting to create a duplicate subscription, the server will close the existing channel, log a warning, and spawn a new channel for the topic. The client will have their channel.onClose callbacks fired for the existing channel, and the new channel join will have its receive hooks processed as normal.

**Comment by happy-san** [comment]
Oh okay! 
Also, can you clarify what do you mean by `topic` ?

**Comment by phamhieu** [comment]
subscription topic is based on your schema and table name.

```
final topic = tableName == '*' ? 'realtime:$schema' : 'realtime:$schema:$tableName';
```

**Comment by happy-san** [comment]
>The client will have their channel.onClose callbacks fired for the existing channel, and the new channel join will have its receive hooks processed as normal.

If I understood correctly, the second subscription should've been successful but they both get closed in my example.

**Comment by happy-san** [comment]
I've updated my subscription to this and everything is working fine! 

``` dart
      _countriesSub =
          _client.from('countries').on(SupabaseEventTypes.all, (x) {
        switch (x.eventType) {
          case 'INSERT':
            print(
                'on countries.insert: ${x.table} ${x.eventType} ${x.newRecord} ');
            break;

          case 'DELETE':
            print(
                'on countries.delete: ${x.table} ${x.eventType} ${x.oldRecord}');
            break;

          case 'UPDATE':
            print(
                'on countries.insert: ${x.table} ${x.eventType} ${x.oldRecord} -> ${x.newRecord} ');
            break;
        }
      }).subscribe((String event, {String errorMsg}) {
        print('event: $event error: $errorMsg');
      });
```
<details>
<summary>...almost</summary>
I'm not receiving anything in `oldRecord` in case of `UPDATE`

``` yaml
I/flutter (15683): on countries.delete: countries DELETE {name: Niger}
I/flutter (15683): on countries.insert: countries INSERT {name: Niger} 
I/flutter (15683): on countries.insert: countries UPDATE {} -> {name: Mexico} 
I/flutter (15683): on countries.insert: countries UPDATE {} -> {name: Mexic} 
I/flutter (15683): on countries.insert: countries UPDATE {} -> {name: Mexico} 
```
 </details>


@phamhieu thank you for your quick response though.

**Comment by phamhieu** [comment]
> I'm not receiving anything in `oldRecord` in case of `UPDATE`

tracking at #9
