### ISSUE TITLE
UPDATE event of SupabaseRealtimePayload gets empty oldRecord.

### ISSUE THREAD

**Issue by happy-san** [supabase/supabase-dart#9]
# Bug report

In the Supabase's table editor window, I did the following in my `todos` table's `task` attribute:
1. Added `o`
2. Edited `o` -> `oOo`
3. Deleted `oOo`

And I got the following result in my dart subscription:

```yaml
I/flutter (21524): todos.INSERT {task: o} 
I/flutter (21524): todos.UPDATE {} -> {task: oOo} 
I/flutter (21524): todos.DELETE {task: oOo}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```dart

void main() {
  SupabaseClient('YOUR-URL-HERE', 'YOUR-ANNON-KEY-HERE').from('todos').on(SupabaseEventTypes.all, (x) {
    switch (x.eventType) {
      case 'INSERT':
        print('${x.table}.${x.eventType} ${x.newRecord} ');
        break;

      case 'DELETE':
        print('${x.table}.${x.eventType} ${x.oldRecord}');
        break;

      case 'UPDATE':
        print('${x.table}.${x.eventType} ${x.oldRecord} -> ${x.newRecord} ');
        break;
    }
  }).subscribe((String event, {String errorMsg}) {
    print('event: $event error: $errorMsg');
  });
}
```
## Expected behavior

The UPDATE event should not have an empty `oldRecord`.

## System information

- OS: EndlessOS
-  Version of supabase-dart: "0.0.1-dev.8"

## Additional context

I've set the `task` attribute as a Primary Key.

**Comment by happy-san** [comment]
Reproducible in `0.0.1-dev.9`

**Comment by w3b6x9** [comment]
@happy-san You're going to have to set the `todos` table's `REPLICA IDENTITY` to `FULL` in order to see old records for updates.

Try `ALTER TABLE public.todos REPLICA IDENTITY FULL;` in Supabase's SQL editor.

**Comment by happy-san** [comment]
@w3b6x9 `ALTER TABLE public.todos REPLICA IDENTITY FULL;` did it for me. Thank you!
